name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Download depot tools
      run: curl https://storage.googleapis.com/chrome-infra/depot_tools.zip --output depot_tools.zip

    - name: Extract depot tools
      run: 7z x depot_tools.zip -odepot_tools

    - name: Prepend depot tools to system path
      run: echo "::add-path::${{ github.workspace }}/depot_tools"

    - name: Initialize gclient
      run: |
        set DEPOT_TOOLS_WIN_TOOLCHAIN=0
        gclient
      shell: cmd

    - name: Check it worked
      run: where python
      shell: cmd

    - name: Clone PDFium
      run: |
        set DEPOT_TOOLS_WIN_TOOLCHAIN=0
        mkdir pdfium_repo
        cd pdfium_repo
        gclient config --unmanaged https://pdfium.googlesource.com/pdfium.git
        gclient sync
        dir .

    - name: Compile PDFium
      run: |
        "./pdfium_repo/pdfium/build/install-build-deps.sh"
        mkdir "./pdfium_repo/pdfium/out"
        copy "args.gn" "./pdfium_repo/pdfium/out/"
        cd "./pdfium_repo/pdfium/"
        gn gen out
        ninja -C out pdfium
      shell: cmd


    #- name: Upload a Build Artifact
    #  uses: actions/upload-artifact@v2
    #  with:
    #    path: out/foo
