name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Download depot tools
      run: curl https://storage.googleapis.com/chrome-infra/depot_tools.zip --output depot_tools.zip

    - name: Extract depot tools
      run: 7z x depot_tools.zip -odepot_tools

    - name: Prepend depot tools to system path
      run: echo "${{ github.workspace }}\depot_tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Initialize gclient
      run: |
        set DEPOT_TOOLS_WIN_TOOLCHAIN=0
        gclient
      shell: cmd

    - name: Create Pfium (Create directory)
      run: |
        set DEPOT_TOOLS_WIN_TOOLCHAIN=0
        mkdir pdfium_repo
      shell: cmd

    - name: Clone PDFium 2 (gclient config)
      run: |
        set DEPOT_TOOLS_WIN_TOOLCHAIN=0
        gclient config --unmanaged https://pdfium.googlesource.com/pdfium.git
      shell: cmd
      working-directory: ./pdfium_repo

    - name: Clone PDFium 3 (Sync repo)
      run: |
        set DEPOT_TOOLS_WIN_TOOLCHAIN=0
        gclient sync
      shell: cmd
      working-directory: ./pdfium_repo

    - name: Clone PDFium 4 (Select branch)
      run: |
        set DEPOT_TOOLS_WIN_TOOLCHAIN=0
        git.exe checkout chromium/4695
        gclient sync
      shell: cmd
      working-directory: ./pdfium_repo/pdfium

    - name: Clone PDFium 5 (Install dependencies)
      # Instead of manually installing pywin32 we probably should execute ./build/install-build-deps.sh
      run: |
        set DEPOT_TOOLS_WIN_TOOLCHAIN=0
        cd ./pdfium_repo/pdfium
        call python.bat -m pip install pywin32
      shell: cmd

    - name: Apply Patches (Copy files)
      run: |
        copy "./ext/PdfiumViewer/Contrib/pdfiumviewer.cpp" "./pdfium_repo/pdfium/fpdfsdk/"
      shell: cmd

    - name: Apply Patches (Git patches)
      run: |
        git.exe apply -v "../../ext/pdfium-binaries/patches/shared_library.patch" --ignore-space-change --ignore-whitespace
        git.exe apply -v "../../ext/pdfium-binaries/patches/public_headers.patch" --ignore-space-change --ignore-whitespace
        git.exe apply -v "../../ext/pdfium-binaries/patches/widestring.patch" --ignore-space-change --ignore-whitespace
        git.exe apply -v "../../include_pdfiumviewer.txt" --ignore-space-change --ignore-whitespace
      shell: cmd
      working-directory: ./pdfium_repo/pdfium

    - name: Compile PDFium x64 1 (copy args)
      run: |
        mkdir "./pdfium_repo/pdfium/out/x64"
        copy "./args.x64.gn" "./pdfium_repo/pdfium/out/x64/args.gn"
      shell: cmd

    - name: Compile PDFium x64 2 (gn)
      run: |
        set DEPOT_TOOLS_WIN_TOOLCHAIN=0
        gn gen ./out/x64
      shell: cmd
      working-directory: ./pdfium_repo/pdfium

    - name: Compile PDFium x64 3 (Ninja)
      run: |
        set DEPOT_TOOLS_WIN_TOOLCHAIN=0
        ninja -C ./out/x64 pdfium
      shell: cmd
      working-directory: ./pdfium_repo/pdfium

    - name: Compile PDFium x64 4 (List directory)
      run: |
        Get-ChildItem -Path . -Filter pdfium.dll -Recurse
      shell: pwsh
      working-directory: ./

    # - name: Upload PDFium DLL x64
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: x64
    #     path: ./pdfium_repo/pdfium/out/x64


    # - name: Compile PDFium x86 1 (copy args)
    #   run: |
    #     mkdir "./pdfium_repo/pdfium/out/x86"
    #     copy "args.x86.gn" "./pdfium_repo/pdfium/out/x86/args.gn"
    #   shell: cmd

    # - name: Compile PDFium x86 2 (gn)
    #   run: |
    #     set DEPOT_TOOLS_WIN_TOOLCHAIN=0
    #     gn gen out/x86
    #   shell: cmd
    #   working-directory: ./pdfium_repo/pdfium

    # - name: Compile PDFium x86 3 (Ninja)
    #   run: |
    #     set DEPOT_TOOLS_WIN_TOOLCHAIN=0
    #     ninja -C out/x86 pdfium
    #   shell: cmd
    #   working-directory: ./pdfium_repo/pdfium

    # - name: Upload PDFium DLL x86
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: x86
    #     path: ./pdfium_repo/pdfium/out/x86/pdfium.dll
