name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Download depot tools
      run: curl https://storage.googleapis.com/chrome-infra/depot_tools.zip --output depot_tools.zip

    - name: Extract depot tools
      run: 7z x depot_tools.zip -odepot_tools

    - name: Prepend depot tools to system path
      run: echo "::add-path::${{ github.workspace }}/depot_tools"

    - name: Initialize gclient
      run: |
        set DEPOT_TOOLS_WIN_TOOLCHAIN=0
        gclient
      shell: cmd

    - name: PDFium
      run: |
        set DEPOT_TOOLS_WIN_TOOLCHAIN=0
        mkdir repo
        cd repo
        gclient config --unmanaged https://pdfium.googlesource.com/pdfium.git
        gclient sync
        cd pdfium
        "./build/install-build-deps.sh"
        mkdir "./out"
        copy "../../args.gn" "./out/"
        gn gen out
        ninja -C out pdfium
      shell: cmd


    #- name: Upload a Build Artifact
    #  uses: actions/upload-artifact@v2
    #  with:
    #    path: out/foo
